# LeadX CRM Analyzer Configuration
# Strict rules for code quality and consistency

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat these as errors (fail CI)
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    invalid_annotation_target: ignore
    # Suppress info-level diagnostics to focus on warnings/errors
    info: ignore
  
  language:
    strict-casts: true
    strict-raw-types: true
  
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
    - "test/**"

linter:
  rules:
    # Error Prevention
    avoid_print: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    throw_in_finally: true
    unnecessary_statements: true
    
    # Style
    prefer_single_quotes: true
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    
    # Documentation
    public_member_api_docs: false  # Enable later for library packages
    
    # Formatting (Disabled for dev speed - purely stylistic)
    always_put_required_named_parameters_first: false  # Stylistic only
    directives_ordering: false  # Import order doesn't affect runtime
    sort_constructors_first: false  # Stylistic ordering
    sort_unnamed_constructors_first: false  # Stylistic ordering
    
    # Code Quality
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catching_errors: true
    avoid_double_and_int_checks: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_js_rounded_ints: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: false  # Minor, not a bug
    avoid_returning_null_for_future: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cascade_invocations: false  # Sometimes reduces readability
    cast_nullable_to_non_nullable: true
    combinators_ordering: true
    conditional_uri_does_not_exist: true
    deprecated_consistency: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    missing_whitespace_between_adjacent_strings: true
    no_runtimeType_toString: true
    noop_primitive_operations: false  # Minor optimization only
    omit_local_variable_types: true
    only_throw_errors: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: false  # Matter of preference
    prefer_if_elements_to_conditional_expressions: true
    prefer_int_literals: true
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    sized_box_shrink_expand: true
    sort_child_properties_last: true
    tighten_type_of_initializing_formals: true
    type_annotate_public_apis: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_lambdas: false  # Closures sometimes clearer
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_to_list_in_spreads: true
    unreachable_from_main: true
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_named_constants: true
    use_raw_strings: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_super_parameters: true
    use_test_throws_matchers: true
    use_to_and_as_if_applicable: true
